[build]
    publish = "./dist"
    command = "yarn build"

[build.environment]
    DISABLE_PHONE_RECOVERY = "no"
    REACT_APP_NETWORK_ID = "default"
    REACT_APP_ACCOUNT_HELPER_URL = "https://helper.mainnet.near.org"
    REACT_APP_NODE_URL = "https://rpc.mainnet.near.org"
    REACT_APP_ACCESS_KEY_FUNDING_AMOUNT = "250000000000000000000000"
    NEW_ACCOUNT_AMOUNT = "500000001000000000000000000"
    REACT_APP_ACCOUNT_ID_SUFFIX = "near"
    EXPLORER_URL = "https://explorer.mainnet.near.org"
    REACT_APP_IS_MAINNET = "true"
    SHOW_PRERELEASE_WARNING = "yes"
    DISABLE_SEND_MONEY = "no"
    DISABLE_CREATE_ACCOUNT = "true"
    REACT_APP_MULTISIG_MIN_AMOUNT = "36"
    LOCKUP_ACCOUNT_ID_SUFFIX = "lockup.near"
    SENTRY_ORG = "near-protocol"
    SENTRY_PROJECT = "mainnet-staging-wallet"
    MOONPAY_API_KEY = "pk_live_jYDdkGL7bJsrwalHZs1lVIhdOHOtK8BR"


[context.production.environment]
    SHOW_PRERELEASE_WARNING = "no"
    BROWSER_MIXPANEL_TOKEN = "6d2d70d539a0c6064e313074ddd097c8"
    SENTRY_PROJECT = "mainnet-wallet"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        Content-Security-Policy = """
            frame-ancestors 'none'
        """

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "@sentry/netlify-build-plugin"
