[build]
    publish = "./dist"
    command = "yarn build"
    ignore = "/bin/false"

[build.environment]
    DISABLE_PHONE_RECOVERY = "yes"
    REACT_APP_NETWORK_ID = "default"
    REACT_APP_ACCOUNT_HELPER_URL = "https://helper.mainnet.near.org"
    REACT_APP_NODE_URL = "https://rpc.mainnet.near.org"
    REACT_APP_ACCESS_KEY_FUNDING_AMOUNT = "250000000000000000000000"
    NEW_ACCOUNT_AMOUNT = "500000001000000000000000000"
    REACT_APP_ACCOUNT_ID_SUFFIX = "near"
    EXPLORER_URL = "https://explorer.mainnet.near.org"
    REACT_APP_IS_MAINNET = "true"
    DISABLE_SEND_MONEY = "no"
    DISABLE_CREATE_ACCOUNT = "true"
    REACT_APP_MULTISIG_MIN_AMOUNT = "4"
    LOCKUP_ACCOUNT_ID_SUFFIX = "lockup.near"
    SENTRY_ORG = "near-protocol"
    SENTRY_PROJECT = "mainnet-staging-wallet"
    MOONPAY_API_KEY = "pk_live_jYDdkGL7bJsrwalHZs1lVIhdOHOtK8BR"
    TOKEN_CONTRACTS = 'berryclub.ek.near,wrap.near,6b175474e89094c44da98b954eedeac495271d0f.factory.bridge.near'
    RECAPTCHA_ENTERPRISE_SITE_KEY = "6LcpJ3EcAAAAAFgA-nixKFNGWMo9IG9FQhH4XjSY"
    RECAPTCHA_CHALLENGE_API_KEY = "6LeRzswaAAAAAGeS7mSasZ1wDcGnMcH3D7W1gy1b"
    NETLIFY_USE_YARN = "true"

[context.production.environment]
    BROWSER_MIXPANEL_TOKEN = "d5bbbbcc3a77ef8427f2b806b5689bf8"
    SENTRY_PROJECT = "mainnet-wallet"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        Content-Security-Policy = """
            frame-ancestors 'none'
        """
[[headers]]
    for = "/auto-import-secret-key*"
    [headers.values]
        X-Robots-Tag = "noindex"
[[headers]]
    for = "/auto-import-seed-phrase*"
    [headers.values]
        X-Robots-Tag = "noindex"
[[headers]]
    for = "/recover-seed-phrase*"
    [headers.values]
        X-Robots-Tag = "noindex"
[[headers]]
    for = "/recover-with-link*"
    [headers.values]
        X-Robots-Tag = "noindex"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
    package = "@sentry/netlify-build-plugin"
