name: Deploy MNW-Testnet

on:
  push:
    branches:
      - testnet

concurrency:
  group: 'testnet'
  cancel-in-progress: true

jobs:
  testnet-live-deploy:
    uses: ./.github/workflows/bundle-and-deploy.yml
    with:
      environment: testnet
      near_wallet_env: testnet
    secrets: inherit
