name: Deploy Preview Bundle

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      s3Bucket:
        required: true
        type: string
    secrets:
      accessKeyId:
        required: true
      deploymentIamRole:
        required: true
      secretAccessKey:
        required: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: frontend-bundle
          path: packages/frontend/dist/${{ inputs.environment }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.accessKeyId }}
          aws-secret-access-key: ${{ secrets.secretAccessKey }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.deploymentIamRole }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
      - run: aws s3 sync dist/${{ inputs.environment }} s3://${{ inputs.s3Bucket }} --delete
